---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.prometheus.persistence.storageClass }}
provisioner: kubernetes.io/no-provisioner   # Utilise cette option si tu utilises un volume statique

