apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prometheus.persistence.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.capacity }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass }}
