---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-internal
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort