grafana:
  persistence:
    name: grafana-pv
    storageClass: "grafana-storage"
    capacity: "1Gi"  # Adjust the size as necessary
  replicaCount: 1
  image: "grafana/grafana"
  services:
    grafana:
      type: ClusterIP
      port: 3000
  resources:
      requests:
        memory: "512M"       # Le conteneur demande au moins 1 Go de RAM
        cpu: "500m"         # Le conteneur demande 0.5 vCPU (un demi processeur)
      limits:
        memory: "2Gi"       # Le conteneur ne pourra pas utiliser plus de 2 Go de RAM
        cpu: "1"            # Le conteneur ne pourra pas utiliser plus de 1 vCPU (un processeur complet)