---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-config
data:
  alertmanager.yml: |-
    {{ tpl .Values.alertmanager.config .| nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-proxy-config
data:
  webhook.py: |
    from flask import Flask, request
    import requests
    import os

    app = Flask(__name__)
    DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")

    @app.route("/webhook", methods=["POST"])
    def alertmanager_to_discord():
        data = request.json
        alerts = data.get("alerts", [])

        for alert in alerts:
            name = alert.get("labels", {}).get("alertname", "Unknown Alert")
            severity = alert.get("labels", {}).get("severity", "unknown")
            description = alert.get("annotations", {}).get("description", "No description")

            message = f"🚨 **{name}**\nSeverity: `{severity}`\n{description}"
            payload = {"content": message}

            r = requests.post(DISCORD_WEBHOOK_URL, json=payload)
            if r.status_code != 204:
                print(f"Failed to send to Discord: {r.text}")

        return "OK", 200

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=8080)