---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-internal
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 9093
      targetPort: 9093
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-external
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30093
  type: NodePort