apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.persistence.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.capacity }}
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
