---
apiVersion: v1
kind: Service
metadata:
  name: grafana-internal
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  type: NodePort